TOPDIR = ../../
#include $(TOPDIR)/Make/makedefs 

C++FILES =\
	ThreadObserver.cpp \
	ThreadReporter.cpp \
	SimpleThreader.cpp

INC      += -I$(TOPDIR)/include
LIBS     += -lOpenThreadPThread

EXEC = SimpleThreader

include $(TOPDIR)/Make/makerules
